-- Temporarily disable RLS to check if data exists
ALTER TABLE managers DISABLE ROW LEVEL SECURITY;
ALTER TABLE rosters DISABLE ROW LEVEL SECURITY;
ALTER TABLE draft_results DISABLE ROW LEVEL SECURITY;
ALTER TABLE players DISABLE ROW LEVEL SECURITY;
ALTER TABLE seasons DISABLE ROW LEVEL SECURITY;
ALTER TABLE trades DISABLE ROW LEVEL SECURITY;
ALTER TABLE toppers DISABLE ROW LEVEL SECURITY;
ALTER TABLE lsl DISABLE ROW LEVEL SECURITY;
ALTER TABLE manager_assets DISABLE ROW LEVEL SECURITY;